export PATH := $(PATH):/home/vizsla/dev/openwrt/trunk/build_dir/target-mips_r2_uClibc-0.9.33.2/OpenWrt-SDK-ar71xx-for-unknown-x86_64-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin

export STAGING_DIR = /home/vizsla/dev/openwrt/trunk/build_dir/target-mips_r2_uClibc-0.9.33.2/OpenWrt-SDK-ar71xx-for-unknown-x86_64-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir
export TOOL = $(STAGING_DIR)/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2
export SDK =/home/vizsla/dev/openwrt/trunk/build_dir/target-mips_r2_uClibc-0.9.33.2/OpenWrt-SDK-ar71xx-for-unknown-x86_64-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-mips_r2_uClibc-0.9.33.2

BINARY = main

OBJS = $(BINARY).o
#OBJS += ant_init.o ant_weighscale.o ant_util.o

LIBS +=  -lmodbus

CC = mips-openwrt-linux-gcc
LD = mips-openwrt-linux-gcc

CFLAGS += -Os -Wall -Wextra -I$(SDK)/usr/include
CFLAGS += -ggdb3
LDFLAGS += -L$(SDK)/usr/lib -L$(TOOL)/lib -L$(TOOL)/usr/lib -Wl,-rpath=$(TOOL)/lib $(LIBS)

all: exe

exe: $(BINARY).exe

%.exe: $(OBJS) 
	$(LD) -o $(*) $(OBJS) $(LDFLAGS)

%.o: %.c Makefile
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f *.o
	rm -f $(BINARY)

.PHONY: exe clean
